INSERT INTO AW_ADMIN.ROLES (ID, NOMBRE) VALUES (1, 'Super-Administrador');
INSERT INTO AW_ADMIN.ROLES (ID, NOMBRE) VALUES (2, 'Administrador');
INSERT INTO AW_ADMIN.ROLES (ID, NOMBRE) VALUES (3, 'Operador');
INSERT INTO AW_ADMIN.ROLES (ID, NOMBRE) VALUES (4, 'Auditor');